# Generated by Django 3.2.2 on 2021-09-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='site',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
