# Generated by Django 3.2.2 on 2021-10-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customeremail', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Mottagen'), (2, 'Skickad')], default=1)),
                ('is_handled', models.BooleanField(default=False, verbose_name='Hanterad')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Betald genom Checkout')),
                ('sessionid', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customeruser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('siteimg', models.FileField(blank=True, null=True, upload_to='images/')),
                ('stripekey', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=150, verbose_name='Produktnamn')),
                ('prodDescription', models.CharField(max_length=500, verbose_name='Produktbeskrivning')),
                ('prodPrice', models.FloatField(blank=True, null=True, verbose_name='Pris')),
                ('prodValnamn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Produktval')),
                ('prodVal1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Val ett')),
                ('prodVal2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Val två')),
                ('prodVal3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Val tre')),
                ('prodImg', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Första produktbilden')),
                ('twoImg', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Andra produktbilden')),
                ('threeImg', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Tredje produktbilden')),
                ('tabNamn1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik ett')),
                ('tabDesc1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik ett')),
                ('tabNamn2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik två')),
                ('tabDesc2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik två')),
                ('tabNamn3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik tre')),
                ('tabDesc3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik tre')),
                ('prodQty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tillgänglig kvantitet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Kategori')),
                ('related', models.ManyToManyField(blank=True, related_name='_core_product_related_+', to='core.Product', verbose_name='Relaterade produkter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produser', to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=150, verbose_name='Produktnamn')),
                ('prodPrice', models.FloatField(blank=True, null=True, verbose_name='Pris')),
                ('prodQty', models.PositiveSmallIntegerField(verbose_name='Antal')),
                ('prodImg', models.CharField(blank=True, max_length=500, null=True)),
                ('prodid', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prodcat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prodVal', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='core.order')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='core.site')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.site'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.site'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
