# Generated by Django 3.2.2 on 2021-09-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prodcat', to='core.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prodDescription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prodPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
