# Generated by Django 3.2.2 on 2021-09-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteContent',
            new_name='Site',
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catsite', to='core.site'),
            preserve_default=False,
        ),
    ]
