# Generated by Django 3.2.2 on 2021-09-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210917_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siteuser', to='accounts.newuser'),
            preserve_default=False,
        ),
    ]
