# Generated by Django 3.2.2 on 2021-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211024_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cuphone',
            field=models.CharField(default=1, max_length=20, verbose_name='Mobilnummer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='siteemail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='from_email'),
        ),
    ]
