# Generated by Django 3.2.6 on 2021-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210919_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodMark',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
