# Generated by Django 3.2.2 on 2021-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211025_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='artno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Artikelnummer'),
        ),
        migrations.AddField(
            model_name='product',
            name='artno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Artikelnummer'),
        ),
    ]
