# Generated by Django 3.2.2 on 2021-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_prodvalnamn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodImgList',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='resized image'),
        ),
    ]
