# Generated by Django 3.2.6 on 2021-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_prodmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodValnamn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
