# Generated by Django 3.2.2 on 2021-10-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_prodimglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodImgList',
        ),
    ]
