# Generated by Django 3.2.2 on 2021-11-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_prodimglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prodImgList',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
