# Generated by Django 3.2.6 on 2021-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitem_prodimglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='footerdesc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
