# Generated by Django 3.2.2 on 2021-11-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_site_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='facebook',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='twitter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
