# Generated by Django 3.2.2 on 2021-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210920_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='stripekey',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
