# Generated by Django 3.2.2 on 2021-09-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_site_stripekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='stripekey',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
