# Generated by Django 3.2.2 on 2021-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_site_stripekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodQty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
