# Generated by Django 3.2.2 on 2021-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_prodqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_core_product_related_+', to='core.Product'),
        ),
    ]
