# Generated by Django 3.2.2 on 2021-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_taxconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
