# Generated by Django 3.2.2 on 2021-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_product_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='siteimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
