# Generated by Django 3.2.2 on 2021-12-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_site_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
