# Generated by Django 3.2.2 on 2021-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210930_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='siteimg',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
