# Generated by Django 3.2.2 on 2021-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211221_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Varumärke/tillverkare'),
        ),
    ]
