# Generated by Django 3.2.2 on 2021-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_site_siteimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodMark',
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
