# Generated by Django 3.2.2 on 2021-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211004_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodName',
            field=models.CharField(max_length=150, verbose_name='Produktnamn'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
