# Generated by Django 3.2.2 on 2021-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nyskick'), (2, 'Begagnad')], default=1),
        ),
    ]
