# Generated by Django 3.2.2 on 2021-10-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20211004_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodDescription',
            field=models.CharField(max_length=500, verbose_name='Produktbeskrivning'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Första produktbilden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodVal1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Val ett'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodVal2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Val två'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodVal3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Val tre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodValnamn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Produktval'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabDesc1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik ett'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabDesc2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik två'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabDesc3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Flikinnehåll för flik tre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabNamn1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik ett'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabNamn2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik två'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tabNamn3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Namn för flik tre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threeImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Tredje produktbilden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='twoImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Andra produktbilden'),
        ),
    ]
