# Generated by Django 3.2.2 on 2021-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taxconversion',
        ),
        migrations.AddField(
            model_name='product',
            name='taxrate',
            field=models.FloatField(default=0.25, verbose_name='Moms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nyskick'), (2, 'Demo'), (3, 'Begagnad'), (4, 'Nedladdning')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Primära produktbilden'),
        ),
    ]
