# Generated by Django 3.2.2 on 2021-10-04 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20211004_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodQty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tillgänglig kvantitet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_core_product_related_+', to='core.Product', verbose_name='Relaterade produkter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produser', to=settings.AUTH_USER_MODEL, verbose_name='Användare'),
        ),
    ]
