# Generated by Django 3.2.6 on 2021-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mottagen'), (2, 'Skickad')], default=1),
            preserve_default=False,
        ),
    ]
