# Generated by Django 3.2.6 on 2021-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FR', 'Mottagen'), ('SC', 'Skickad')], max_length=2),
        ),
    ]
