# Generated by Django 3.2.6 on 2021-10-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_handled',
            field=models.BooleanField(default=False, verbose_name='Hanterad'),
        ),
    ]
